- name: Install packages
  apt: name={{item}}
  with_items:
    - ack
    - htop
    - curl 
    - gcc 
    - git 
    - cmake 
    - python-dev 
    - python3-all-dev 
    - tmux 
    - lnav 
    - zsh 
    - g++
    - tree
    - golang-go
  become: true

