- name: check if has GUI
  command: "dpkg-query -W 'ubuntu-desktop'"
  register: is_desktop
  ignore_errors: yes
- debug: msg="{{is_desktop}}"

- name: Install snap application
  become: true
  snap: 
    classic: yes
    name:
      - lxd
      - juju
      - juju-crashdump
      - juju-wait
      - charm
      - kubectl
      - openstackclients
        #        - multipass
    
- name: Install GUI snap application
  when: is_desktop is not failed
  become: true
  snap:
    classic: yes
    name:
      - chromium
      - code
      - slack
      - snapcraft
      - spotify
      - telegram-desktop
      - vlc
 
