- name: create .vim folder
  file:
    path: ~/.vim
    state: directory
    mode: 0755

- name: create .vim/autoload folder
  file:
    path: ~/.vim/autoload
    state: directory
    mode: 0755

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: copy vimrc
  copy: src=../files/vimrc dest=~/.vimrc

- name: Install plugs
  shell: vim -c PlugInstall -c qa

- name: enable 'colorscheme solarized' in vimrc
  lineinfile:
    path: ~/.vimrc
    regexp: \"colorscheme solarized
    line: colorscheme solarized
