- hosts: localhost
  #  vars:
  #    local_home: "{{ lookup('env', 'HOME') }}"
  tasks:
    - include: roles/tasks/packages.yml
    - include: roles/tasks/tmux.yml
    - include: roles/tasks/zsh.yml
    - include: roles/tasks/fzf.yml
    - include: roles/tasks/vim.yml

