- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: roles/tasks/packages.yml
    - include: roles/tasks/tmux.yml
    - include: roles/tasks/zsh.yml
    - include: roles/tasks/fzf.yml
    - include: roles/tasks/vim.yml

